# Generated by Django 4.2.7 on 2025-09-07 08:57

import citizen_reports.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('report_type', models.CharField(choices=[('general', 'General Corruption Report'), ('tender', 'Tender-related Issue'), ('bribery', 'Bribery/Extortion'), ('misuse', 'Misuse of Public Resources'), ('nepotism', 'Nepotism/Favoritism'), ('other', 'Other')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('specific_location', models.CharField(blank=True, max_length=200)),
                ('reporter_name', models.CharField(blank=True, max_length=100)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('reporter_phone', models.CharField(blank=True, max_length=20)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('false_report', 'False Report'), ('resolved', 'Resolved')], default='submitted', max_length=15)),
                ('admin_notes', models.TextField(blank=True)),
                ('content_hash', models.CharField(editable=False, max_length=64)),
                ('submission_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.district')),
                ('related_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizen_reports', to='dashboard.organization')),
                ('related_tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizen_reports', to='dashboard.tender')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio Recording'), ('document', 'Document'), ('video', 'Video'), ('other', 'Other')], max_length=10)),
                ('file', models.FileField(upload_to=citizen_reports.models.upload_to_reports, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx', 'mp3', 'wav', 'mp4', 'avi', 'txt'])])),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('file_hash', models.CharField(editable=False, max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='citizen_reports.citizenreport')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrityReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('evidence_hashes', models.JSONField(default=list)),
                ('previous_receipt_hash', models.CharField(blank=True, max_length=64)),
                ('merkle_root', models.CharField(editable=False, max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integrity_receipt', to='citizen_reports.citizenreport')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='citizenreport',
            index=models.Index(fields=['report_id'], name='citizen_rep_report__df8324_idx'),
        ),
        migrations.AddIndex(
            model_name='citizenreport',
            index=models.Index(fields=['status'], name='citizen_rep_status_3fc342_idx'),
        ),
        migrations.AddIndex(
            model_name='citizenreport',
            index=models.Index(fields=['report_type'], name='citizen_rep_report__ca4637_idx'),
        ),
        migrations.AddIndex(
            model_name='citizenreport',
            index=models.Index(fields=['district'], name='citizen_rep_distric_cec11d_idx'),
        ),
        migrations.AddIndex(
            model_name='citizenreport',
            index=models.Index(fields=['submitted_at'], name='citizen_rep_submitt_64812a_idx'),
        ),
    ]
